# Generated by Django 4.2 on 2023-05-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descrption',
            new_name='description',
        ),
    ]
