# Generated by Django 4.2 on 2023-05-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
